apiVersion: v2
description: No Fault Divorce - CCD Definitions
name: nfdiv-ccd-definitions
version: 2.0.1
dependencies:
  - name: nodejs
    version: ~2.3.4
    repository: '@hmctspublic'
  - name: ccd
    version: ~4.3.2
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr